services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
    

volumes:
  static:
  postgres_data: