services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - ./backend/:/usr/local/app
    env_file:
      - .env.prod    
    expose:
      - 8000      
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17.2-alpine3.20
    env_file:
      - .env.prod.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:      
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    

    